### ISSUE TITLE
Android share image from MMS does not work

### ISSUE THREAD

**Issue by gbelfingerivs** [bhagat-techind/flutter_sharing_intent#24]
flutter_sharing_intent: 1.0.6
device: Google Pixel 6
android: 13

Sharing a photo from MMS does not work (app crashes).

I added some logs to try to debug it and it seems that you are missing that catch block. When I added the catch block everything works even in case of MMS share.

<img width="849" alt="image" src="https://github.com/bhagat-techind/flutter_sharing_intent/assets/96905660/33d49e67-2d49-4acf-a0a2-9095fa52ba06">

W/com.techind.flutter_sharing_intent.FlutterSharingIntentPlugin( 6320): handleIntent ==>> android.intent.action.SEND, image/jpeg
I/FileDirectory( 6320): Uri: content://com.google.android.apps.messaging.shared.datamodel.ProxyProvider/-6055013842676276567.jpg
I/FileDirectory( 6320): Column names: _display_name
I/FileDirectory( 6320): Column index: 0
I/FileDirectory( 6320): Column0 type: 0
I/FileDirectory( 6320): File name: null
D/AndroidRuntime( 6320): Shutting down VM
E/AndroidRuntime( 6320): FATAL EXCEPTION: main
E/AndroidRuntime( 6320): Process: xxx, PID: 6320
E/AndroidRuntime( 6320): java.lang.NullPointerException
E/AndroidRuntime( 6320): 	at java.io.File.<init>(File.java:363)
E/AndroidRuntime( 6320): 	at com.techind.flutter_sharing_intent.MyFileDirectory.getDataColumn(MyFileDirectory.kt:115)
E/AndroidRuntime( 6320): 	at com.techind.flutter_sharing_intent.MyFileDirectory.getAbsolutePath(MyFileDirectory.kt:80)
E/AndroidRuntime( 6320): 	at com.techind.flutter_sharing_intent.FlutterSharingIntentPlugin.getSharingUris(FlutterSharingIntentPlugin.kt:132)
E/AndroidRuntime( 6320): 	at com.techind.flutter_sharing_intent.FlutterSharingIntentPlugin.handleIntent(FlutterSharingIntentPlugin.kt:96)
E/AndroidRuntime( 6320): 	at com.techind.flutter_sharing_intent.FlutterSharingIntentPlugin.onNewIntent(FlutterSharingIntentPlugin.kt:246)
E/AndroidRuntime( 6320): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onNewIntent(FlutterEngineConnectionRegistry.java:832)

**Comment by gbelfingerivs** [comment]
Do you have any news regarding this?

**Comment by cmerchant** [comment]
I have the same issue.
