### ISSUE TITLE
Not able to share anything from external files to the application in ios

### ISSUE THREAD

**Issue by dhairyajain29** [bhagat-techind/flutter_sharing_intent#59]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getInitialSharing on channel flutter_sharing_intent)

Dart - 3.0.0
Flutter SDK - 3.19.2

This is the same sample app we tried for flutter share intent - https://github.com/dhairyajain29/fluttersharingdemo1

Full error below

Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           44.2s
[ERROR:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalImpeller.mm(42)] Using the Impeller rendering backend.
Debug service listening on ws://127.0.0.1:51520/6MrLxEg2BaM=/ws
Syncing files to device iPhone 15 Pro...
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getInitialSharing on channel flutter_sharing_intent)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannelFlutterSharingIntent.getInitialSharing (package:flutter_sharing_intent/flutter_sharing_intent_method_channel.dart:29:18)
<asynchronous suspension>
#2      _MyAppState.initState.<anonymous closure> (package:fluttersharingdemo1/main.dart:38:15)
<asynchronous suspension>

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel flutter_sharing_intent/events-sharing:
MissingPluginException(No implementation found for method listen on channel flutter_sharing_intent/events-sharing)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676:9)
<asynchronous suspension>
====================================================================================================

**Comment by matthiaswinfried** [comment]
same here

**Comment by bhagat-techind** [comment]
Thanks for reporting this!
The issue has been fixed in the latest version.
Closing this now — feel free to reopen if you still face the problem.
